name: GitHub Actions
on:
  push:
    branches:
      - prod
      - master
      - alpha
      - beta 

jobs:
  container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.18, 18.12]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.MFE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MFE_AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
    steps:
     
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx playwright install-deps
      - name: Python pkg setup and codeartifact login 
        run: |
          apt-get update && apt-get install -y python3-pip
          pip3 install -U awscli
          aws --version
          aws codeartifact login --tool npm --repository livspace_npm_private --domain livspace-private
      - run: npm ci
      - name: Set package.json version as $GITHUB_ENV
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Publish 
        env: 
          PACKAGE_VERSION: '${{ fromJson(env.PACKAGE_JSON).version }}' 
        run: |
          echo "${GITHUB_REF#refs/heads/}"
          npm publish
           
      
    
      
      
