name: GitHub Actions for Texture-mfe
on:
  push:
    branches:
      - prod
      - master
      - alpha
      - beta 

jobs:
  container:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.MFE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.MFE_AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
    container: node:12.19
    steps:
      - name: Python pkg setup and codeartifact login 
        run: |
          apt-get update && apt-get install -y python3-pip
          pip3 install -U awscli
          aws --version
          aws codeartifact login --tool npm --repository livspace_npm_group --domain livspace-private 
      - name: Check out repository code
        uses: actions/checkout@v3  
        with:
          path: ${{ github.workspace }}
      - name : NPM install
        run: npm i
      - name: Run  Unit Test case 
        run: npm run test
      - name: Package Bundle
        run : npm run bundle
      - name: Set package.json version as $GITHUB_ENV
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV 
      - name: SEMANTIC_VERSION setup and mv command
        env: 
          PACKAGE_VERSION: '${{ fromJson(env.PACKAGE_JSON).version }}' 
        run : |
          echo $PACKAGE_VERSION
          mv dist $PACKAGE_VERSION  
      - name: S3 deploy 
        env: 
          PACKAGE_VERSION: '${{ fromJson(env.PACKAGE_JSON).version }}' 
        run: |
          echo "${GITHUB_REF#refs/heads/}"
          aws configure list
          aws s3 sync ./$PACKAGE_VERSION s3://${{secrets.AWS_BUCKET_NAME}}/material${GITHUB_REF#refs/heads}/$PACKAGE_VERSION/
      
    
      
      
